### ISSUE TITLE
Access token is not available

### ISSUE THREAD

**Issue by SteveALee** [atomrc/cyclejs-auth0#6]
The token passed to the decorators is the OpenID id_token when it needs to be the access_token. 
Has it actually ever worked with the idtoken? If so then I'm confused.

The Lock 'authenticated' even returns both if the opened scope is specified.

It would be a breaking change but I suggest the token$ payload is something more like
```
{ 
  id: id_token,
  access: access_token,
  refresh: refresh token
}
```

I've not figured how to safely  get a refresh token in a web app

**Comment by atomrc** [comment]
Hi @SteveALee sorry for replying so late :/

Indeed, not returning the `accessToken` can be problematic (and now with the `getProfile` method being deprecated, it's even more important to be able get the accessToken).

Returning all the tokens in the `token$` seems to be the right way to do this. 
I'll try to update the lib soon :)

**Comment by pauldailly** [comment]
Hi there, I too have run into an issue whereby I would like to decorate an HTTP sink with the access token as opposed to the id token. From (my understanding of) the initial problem statement by @SteveALee, it seemed the intention of raising this issue was so that decorator functions would be passed both the access and id tokens? However, it seems that decorator functions are still [passed only the id token](https://github.com/atomrc/cyclejs-auth0/blob/master/src/AuthenticationWrapper.js#L26). 

Apologies if I have misunderstood the issue being raised here. However I just wanted to gain a bit more insight on the reason behind the access token not being made available to the decorator functions.

**Comment by atomrc** [comment]
Hi @pauldailly oh you are completely right, I totally forgot to update the decorator function arguments. 
I guess I could send the whole `tokens` object (also meaning new major version as this is a breaking change). Would that work for you?

Feel free to create a PR if you feel like it, I'd be happy to merge it. 
Else, I'll try to do this as soon as possible.

Thanks for the report BTW :)

**Comment by pauldailly** [comment]
Hi @atomrc thanks for your reply. Yeah I'd be happy to look at this and create a PR. In terms of the signature of the decorator function I did think about the option of passing the access token as a third param. This would mean the function signature would look like:

```decorate(data, tokens.idToken, tokens.accessToken)```

On one hand, although this would technically be backwards compatible, it's perhaps a bit less clean that just passing the `tokens` object as a whole. I'm happy to go whichever way you would prefer however. Just let me know your thoughts and I can work on a PR.

Thanks for your help.

**Comment by atomrc** [comment]
I think we can go with feeding the full `tokens` object to the `decorate` function. 
This way we will be consistent with what the `tokens$` stream emits :)
