### ISSUE TITLE
Uncaught TypeError: xstream_1.default.fromObservable(...).subscribe is not a function

### ISSUE THREAD

**Issue by alexbepple** [atomrc/cyclejs-auth0#8]
Sorry for the bad title, but I could not come up with anything more specific.

I started trying to follow https://auth0.com/docs/quickstart/spa/cyclejs. It turns out that almost every component has seen a major update since then. With the current versions I ran into this issue:

    Uncaught TypeError: xstream_1.default.fromObservable(...).subscribe is not a function
        at http://localhost:3012/bundle.js:1433:85
        at Array.map (native)
        at replicateMany (http://localhost:3012/bundle.js:1433:10)
        at run (http://localhost:3012/bundle.js:1513:34)
        at run (http://localhost:3012/bundle.js:1555:12)
        at Object.1.@cycle/dom (http://localhost:3012/bundle.js:33:19)
        at s (http://localhost:3012/bundle.js:1:254)
        at e (http://localhost:3012/bundle.js:1:425)
        at http://localhost:3012/bundle.js:1:443

Any ideas?

Kindly use https://github.com/alexbepple/cyclejs-auth0-issue to reproduce.

**Comment by atomrc** [comment]
Hi @alexbepple sorry for not replying earlier, I just came back from holidays :)

Ok so the problem is that you have installed `@cycle/run` while you should have installed `@cycle/xstream-run` to work with the `xstream` lib.

I guess that should fix your problem.

Concerning the auth0 docs, I created a PR before my holidays, but there is no update on it. https://github.com/auth0/docs/pull/3540
